default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: task_manager_development

test:
  <<: *default
  database: task_manager_test

production:
  primary: &primary_production
    <<: *default
    database: task_manager_production
  cache:
    <<: *primary_production
    database: task_manager_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: task_manager_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: task_manager_production_cable
    migrations_paths: db/cable_migrate
