default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: pierre
  password:
  pool: 5
  port: 5432

development:
  <<: *default
  database: task_manager_development

test:
  <<: *default
  database: task_manager_test

production:
  <<: *default
  database: task_manager_production

